namespace VRBuilder.TextToSpeech.Audio
{
    /// <summary>
    /// Interface implemented by content generated by a TTS provider for multiple languages.
    /// </summary>
    public interface IVRBTextToSpeechContent
    {
        ///// <summary>
        ///// True if a generated file for this content exists in the project.
        ///// </summary>
        bool IsCached { get; }

        /// <summary>
        /// English Text content to be fed to the TTS provider.
        /// </summary>
        string EnglishText { get; }

        /// <summary>
        /// Hindi Text content to be fed to the TTS provider.
        /// </summary>
        string HindiText { get; }

        /// <summary>
        /// Tamil Text content to be fed to the TTS provider.
        /// </summary>
        string TamilText { get; }
    }
}
